# Generated by Django 2.1.7 on 2020-08-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200809_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='physicaly_impaired',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='physicaly_impaired_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
