# Generated by Django 2.1.7 on 2020-08-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200809_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifications',
            name='details',
            field=models.TextField(default='None'),
        ),
    ]
