# Generated by Django 2.1.7 on 2020-08-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_personalfileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalfileupload',
            name='kcse_cert',
            field=models.FileField(blank=True, null=True, upload_to='kcsecert'),
        ),
    ]
